# Generated by Django 4.0.3 on 2022-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_record_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
